import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { 
  Trophy, 
  Brain, 
  Sparkles, 
  Clock, 
  Users, 
  BookOpen, 
  ArrowRight, 
  CheckCircle2, 
  XCircle,
  HelpCircle,
  TrendingUp,
  MessageSquareQuote
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { SessionSummary, QuizQuestion } from '../lib/gemini';
import { db, doc, updateDoc, increment, collection, query, orderBy, limit, getDocs } from '../lib/firebase';
import { toast } from 'sonner';

interface AppSessionSummaryProps {
  userData: any;
  duration: number;
  mode: string;
  topic: string;
  materials: string;
  summary: SessionSummary;
  onClose: () => void;
}

export default function AppSessionSummary({ 
  userData, 
  duration, 
  mode, 
  topic, 
  materials, 
  summary, 
  onClose 
}: AppSessionSummaryProps) {
  const [reflection, setReflection] = useState('');
  const [quizStarted, setQuizStarted] = useState(false);
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [userAnswers, setUserAnswers] = useState<number[]>([]);
  const [showResults, setShowResults] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [history, setHistory] = useState<any[]>([]);

  // Fetch recent session history to identify progress patterns
  React.useEffect(() => {
    const fetchHistory = async () => {
      if (!userData?.uid) return;
      try {
        const q = query(
          collection(db, 'users', userData.uid, 'sessions'),
          orderBy('startTime', 'desc'),
          limit(3)
        );
        const snapshot = await getDocs(q);
        setHistory(snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() })));
      } catch (err) {
        console.error("Error fetching session history", err);
      }
    };
    if (showResults) fetchHistory();
  }, [userData?.uid, showResults]);

  const pointsEarned = duration + (mode === 'friend' ? 50 : 0) + (duration >= 45 ? 25 : 0);
  const levelBefore = Math.floor((userData?.totalStudyTime || 0) / 3600) + 1;
  const levelAfter = Math.floor(((userData?.totalStudyTime || 0) + duration * 60) / 3600) + 1;

  const handleAnswerSelection = (index: number) => {
    const newAnswers = [...userAnswers];
    newAnswers[currentQuestionIndex] = index;
    setUserAnswers(newAnswers);
  };

  const nextQuestion = () => {
    if (currentQuestionIndex < summary.quiz.length - 1) {
      setCurrentQuestionIndex(prev => prev + 1);
    } else {
      setShowResults(true);
    }
  };

  const handleFinish = async () => {
    setIsSaving(true);
    try {
      const userRef = doc(db, 'users', userData.uid);
      const updateData: any = {
        totalQuizzesTaken: increment(1),
        totalCorrectAnswers: increment(correctAnswersCount),
        totalQuizQuestions: increment(summary.quiz.length)
      };
      
      if (reflection) {
        updateData.reflections = increment(1);
      }
      
      await updateDoc(userRef, updateData);
      toast.success("Progress saved.");
      onClose();
    } catch (error) {
      toast.error("Failed to save progress.");
    } finally {
      setIsSaving(false);
    }
  };

  // Calculate performance metrics for the post-session summary
  // totalQuestions: The number of questions generated by Gemini for this session
  // correctAnswersCount: The total number of questions where the index of the user's choice 
  // matches the index of the correctAnswer field in the question object.
  const correctAnswersCount = userAnswers.filter((ans, idx) => ans === summary.quiz[idx].correctAnswer).length;
  // accuracyRate: Percentage of correct answers (0-100)
  const accuracyRate = Math.round((correctAnswersCount / summary.quiz.length) * 100);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-md overflow-y-auto">
      <motion.div 
        initial={{ opacity: 0, y: 20, scale: 0.95 }}
        animate={{ opacity: 1, y: 0, scale: 1 }}
        className="w-full max-w-4xl bg-white rounded-[2.5rem] shadow-2xl overflow-hidden my-auto"
      >
        <div className="relative h-32 bg-indigo-500 overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-r from-indigo-500 to-purple-600 opacity-90" />
          <div className="absolute inset-0 opacity-10">
            <TrendingUp className="absolute top-4 left-4 h-24 w-24 rotate-12" />
            <Trophy className="absolute bottom-4 right-4 h-20 w-20 -rotate-12" />
          </div>
          <div className="relative z-10 h-full flex flex-col items-center justify-center text-white px-6">
            <Badge variant="secondary" className="mb-2 bg-white/20 text-white border-none backdrop-blur-md underline-offset-4">
              Session Summary
            </Badge>
            <h1 className="text-3xl font-bold tracking-tight">Session complete.</h1>
          </div>
        </div>

        <div className="p-8 space-y-8 max-h-[80vh] overflow-y-auto">
          {/* Overview Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card className="border-none bg-slate-50/50 rounded-3xl overflow-hidden">
              <CardHeader className="pb-2">
                <CardTitle className="text-sm font-bold uppercase tracking-widest text-slate-400 flex items-center gap-2">
                  <Clock className="w-4 h-4" /> Session Stats
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="flex justify-between items-center text-slate-600">
                  <span className="flex items-center gap-2 font-medium">Topic:</span>
                  <span className="font-bold text-slate-900">{topic || 'General'}</span>
                </div>
                <div className="flex justify-between items-center text-slate-600">
                  <span className="flex items-center gap-2 font-medium">Duration:</span>
                  <span className="font-bold text-slate-900">{duration} minutes</span>
                </div>
                <div className="flex justify-between items-center text-slate-600">
                  <span className="flex items-center gap-2 font-medium">Mode:</span>
                  <Badge className={mode === 'friend' ? 'bg-indigo-500' : 'bg-slate-400'}>
                    {mode === 'friend' ? 'With others' : 'Solo'}
                  </Badge>
                </div>
                <div className="pt-4 border-t border-slate-100">
                  <div className="flex items-center gap-2 text-sm text-slate-500 mb-2">
                    <TrendingUp className="w-4 h-4 text-emerald-500" />
                    Productivity Insight
                  </div>
                  <p className="text-slate-600 text-sm leading-relaxed italic border-l-2 border-indigo-200 pl-3">
                    "{summary.productivityInsight}"
                  </p>
                </div>
              </CardContent>
            </Card>

            <Card className="border-none bg-indigo-50/30 rounded-3xl overflow-hidden">
              <CardHeader className="pb-2">
                <CardTitle className="text-sm font-bold uppercase tracking-widest text-indigo-400 flex items-center gap-2">
                  <Sparkles className="w-4 h-4" /> Gamification
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="flex items-center gap-4 bg-white p-4 rounded-2xl shadow-sm">
                  <div className="w-12 h-12 bg-yellow-400 rounded-xl flex items-center justify-center shadow-lg transform -rotate-6">
                    <Trophy className="w-6 h-6 text-white" />
                  </div>
                  <div>
                    <p className="text-xs font-bold text-slate-400 uppercase tracking-tighter">Points Earned</p>
                    <p className="text-2xl font-black text-slate-800">+{pointsEarned}</p>
                  </div>
                </div>

                <div className="space-y-2">
                  <div className="flex justify-between text-sm font-bold">
                    <span className="text-slate-600">Level {levelAfter}</span>
                    <span className="text-indigo-500">{(userData?.totalStudyTime % 3600) / 36}% to next</span>
                  </div>
                  <Progress value={((userData?.totalStudyTime + duration * 60) % 3600) / 36} className="h-3 bg-slate-100" />
                  {levelAfter > levelBefore && (
                    <p className="text-xs font-bold text-emerald-500 animate-bounce">LEVEL UP ACHIEVED! 🚀</p>
                  )}
                </div>

                <p className="text-slate-500 text-xs text-center border-t border-indigo-100/50 pt-4">
                  {summary.motivationalMessage}
                </p>
              </CardContent>
            </Card>
          </div>

          {/* AI Summary Section */}
          <section className="space-y-4">
            <h3 className="text-xl font-bold text-slate-800 flex items-center gap-2">
              <Brain className="w-6 h-6 text-indigo-500" /> Key Material Summary
            </h3>
            <div className="bg-slate-50 p-6 rounded-3xl border border-slate-100 text-slate-600 leading-relaxed">
              {summary.summary}
            </div>
          </section>

          {/* Quiz Section */}
          <section className="space-y-4">
            <h3 className="text-xl font-bold text-slate-800 flex items-center gap-2">
              <CheckCircle2 className="w-6 h-6 text-emerald-500" /> Knowledge Check
            </h3>
            {!quizStarted ? (
              <Card className="border-2 border-dashed border-slate-200 rounded-3xl hover:border-emerald-200 transition-colors cursor-pointer group" onClick={() => setQuizStarted(true)}>
                <CardContent className="py-12 flex flex-col items-center">
                  <div className="w-16 h-16 bg-emerald-50 rounded-full flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                    <BookOpen className="w-8 h-8 text-emerald-500" />
                  </div>
                  <h4 className="text-lg font-bold text-slate-700 mb-2">Check retention</h4>
                  <p className="text-slate-400 text-sm mb-6">Answer {summary.quiz.length} questions from your study material.</p>
                  <Button className="rounded-full bg-emerald-500 hover:bg-emerald-600 px-8">Start quiz</Button>
                </CardContent>
              </Card>
            ) : !showResults ? (
              <Card className="border-none bg-emerald-50/30 rounded-3xl overflow-hidden shadow-sm">
                <CardHeader className="flex flex-row items-center justify-between pb-2">
                  <div className="space-y-1">
                    <CardTitle className="text-sm font-bold text-emerald-600">Question {currentQuestionIndex + 1} of {summary.quiz.length}</CardTitle>
                  </div>
                  <Badge variant="outline" className="bg-white text-emerald-500 border-emerald-100">
                    {Math.round(((currentQuestionIndex + 1) / summary.quiz.length) * 100)}%
                  </Badge>
                </CardHeader>
                <CardContent className="p-8 space-y-6">
                  <h4 className="text-lg font-bold text-slate-800 leading-tight">
                    {summary.quiz[currentQuestionIndex].question}
                  </h4>
                  <div className="grid gap-3">
                    {summary.quiz[currentQuestionIndex].options.map((option, idx) => (
                      <button
                        key={idx}
                        onClick={() => handleAnswerSelection(idx)}
                        className={`w-full text-left p-4 rounded-2xl border-2 transition-all font-medium ${
                          userAnswers[currentQuestionIndex] === idx
                            ? 'border-emerald-500 bg-emerald-50 text-emerald-700'
                            : 'border-white bg-white hover:border-slate-200 text-slate-600'
                        }`}
                      >
                        {option}
                      </button>
                    ))}
                  </div>
                  <Button 
                    onClick={nextQuestion} 
                    disabled={userAnswers[currentQuestionIndex] === undefined}
                    className="w-full rounded-2xl py-6 bg-emerald-500 hover:bg-emerald-600 text-lg shadow-lg shadow-emerald-100"
                  >
                    {currentQuestionIndex < summary.quiz.length - 1 ? 'Next' : 'Results'}
                  </Button>
                </CardContent>
              </Card>
            ) : (
              <div className="space-y-6">
                <Card className="border-none bg-emerald-500 rounded-[2.5rem] text-white shadow-xl overflow-hidden relative">
                  <div className="absolute top-0 right-0 p-8 opacity-10">
                    <Trophy className="w-32 h-32 rotate-12" />
                  </div>
                  <CardContent className="p-10 flex flex-col items-center text-center relative z-10">
                    <div className="bg-white/20 p-4 rounded-full mb-6 backdrop-blur-sm">
                      <TrendingUp className="w-12 h-12" />
                    </div>
                    <h4 className="text-3xl font-black mb-2">Quiz Mastery</h4>
                    <p className="text-white/80 mb-6 max-w-xs font-medium">
                      You answered {correctAnswersCount} out of {summary.quiz.length} questions correctly, for a {accuracyRate}% accuracy rate.
                    </p>
                    
                    <div className="grid grid-cols-3 gap-4 w-full">
                      <div className="bg-white/10 rounded-2xl p-4 backdrop-blur-sm">
                        <p className="text-[10px] font-bold uppercase tracking-widest text-white/60 mb-1">Total</p>
                        <p className="text-2xl font-black">{summary.quiz.length}</p>
                      </div>
                      <div className="bg-emerald-400/30 rounded-2xl p-4 backdrop-blur-sm">
                        <p className="text-[10px] font-bold uppercase tracking-widest text-emerald-100 mb-1">Correct</p>
                        <p className="text-2xl font-black">{correctAnswersCount}</p>
                      </div>
                      <div className="bg-rose-400/30 rounded-2xl p-4 backdrop-blur-sm">
                        <p className="text-[10px] font-bold uppercase tracking-widest text-rose-100 mb-1">Missed</p>
                        <p className="text-2xl font-black">{summary.quiz.length - correctAnswersCount}</p>
                      </div>
                    </div>
                  </CardContent>
                </Card>

                {/* Performance Patterns */}
                <Card className="border-2 border-slate-100 rounded-[2.5rem] overflow-hidden">
                  <CardHeader className="pb-2">
                    <CardTitle className="text-lg font-bold flex items-center gap-2">
                      <Sparkles className="w-5 h-5 text-amber-500" /> Topic Performance
                    </CardTitle>
                    <CardDescription>Patterns identified in your current session</CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-6">
                    <div className="space-y-4">
                      {/* 
                        Performance Analysis Logic:
                        1. Group questions by their AI-assigned category.
                        2. Calculate correct vs total per category.
                        3. Visualize as colored progress bars.
                      */}
                      {Object.entries(
                        summary.quiz.reduce((acc, q, idx) => {
                          const cat = q.category || 'General';
                          if (!acc[cat]) acc[cat] = { total: 0, correct: 0 };
                          acc[cat].total++;
                          if (userAnswers[idx] === q.correctAnswer) acc[cat].correct++;
                          return acc;
                        }, {} as Record<string, { total: number, correct: number }>)
                      ).map(([cat, stats]) => {
                        const score = Math.round((stats.correct / stats.total) * 100);
                        return (
                          <div key={cat} className="group">
                            <div className="flex justify-between items-end mb-2">
                              <div className="flex items-center gap-2">
                                <span className="text-sm font-bold text-slate-700">{cat}</span>
                                {score >= 80 ? (
                                  <Badge className="bg-emerald-100 text-emerald-700 text-[8px] font-black uppercase tracking-widest border-none h-4">Strength</Badge>
                                ) : score < 60 ? (
                                  <Badge className="bg-rose-100 text-rose-700 text-[8px] font-black uppercase tracking-widest border-none h-4">Need Focus</Badge>
                                ) : null}
                              </div>
                              <span className={`text-sm font-black ${score >= 80 ? 'text-emerald-500' : score >= 50 ? 'text-amber-500' : 'text-rose-500'}`}>
                                {score}%
                              </span>
                            </div>
                            <div className="h-2 w-full bg-slate-100 rounded-full overflow-hidden">
                              <motion.div 
                                initial={{ width: 0 }}
                                animate={{ width: `${score}%` }}
                                className={`h-full rounded-full ${score >= 80 ? 'bg-emerald-500' : score >= 50 ? 'bg-amber-500' : 'bg-rose-500'}`}
                              />
                            </div>
                          </div>
                        );
                      })}
                    </div>

                    <div className="pt-4 border-t border-slate-100">
                      <div className="bg-slate-50 p-6 rounded-3xl space-y-4">
                        <div className="flex gap-4 items-start">
                          <div className="w-10 h-10 bg-indigo-100 rounded-xl flex items-center justify-center shrink-0">
                            <Brain className="w-5 h-5 text-indigo-600" />
                          </div>
                          <div>
                            <p className="text-xs font-bold text-indigo-600 uppercase tracking-widest mb-1">Learning Focus</p>
                            <p className="text-sm text-slate-600 leading-relaxed">
                              {accuracyRate === 100 
                                ? "Mastery achieved! You've perfectly grasped every concept in this session. Challenge yourself with harder quiz levels next time."
                                : accuracyRate > 70
                                ? "Great progress. You have a solid foundation, especially in your 'Strength' areas. A quick review of the missed explanations will close the remaining gaps."
                                : "A productive session, but some core concepts need more attention. Focus your next study block on the 'Need Focus' topics highlighted above."
                              }
                            </p>
                          </div>
                        </div>

                        {history.length > 0 && (
                          <div className="pt-4 border-t border-indigo-100 flex items-center justify-between">
                            <div className="flex items-center gap-2">
                              <TrendingUp className="w-4 h-4 text-emerald-500" />
                              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Recent Activity Trend</span>
                            </div>
                            <div className="flex gap-1">
                              {history.map((_, i) => (
                                <div key={i} className="w-2 h-4 bg-indigo-200 rounded-full opacity-40" />
                              ))}
                              <div className="w-2 h-4 bg-indigo-500 rounded-full" title="Current session" />
                            </div>
                          </div>
                        )}
                      </div>
                    </div>
                  </CardContent>
                </Card>

                {/* Review List */}
                <div className="grid gap-3">
                  <h5 className="text-sm font-bold text-slate-400 uppercase tracking-widest ml-4">Detailed Review</h5>
                  {summary.quiz.map((q, idx) => (
                    <div key={idx} className="flex gap-4 p-5 rounded-3xl bg-white border border-slate-100 shadow-sm items-start">
                      <div className={`w-8 h-8 rounded-full shrink-0 flex items-center justify-center ${userAnswers[idx] === q.correctAnswer ? 'bg-emerald-100 text-emerald-600' : 'bg-rose-100 text-rose-600'}`}>
                        {userAnswers[idx] === q.correctAnswer ? <CheckCircle2 className="w-5 h-5" /> : <XCircle className="w-5 h-5" />}
                      </div>
                      <div className="space-y-1 flex-1">
                        <p className="text-sm font-bold text-slate-800">{q.question}</p>
                        <p className="text-xs text-slate-500">
                          <span className="font-bold">Result:</span> {userAnswers[idx] === q.correctAnswer ? 'Correct' : `Incorrect (You chose: ${q.options[userAnswers[idx]]})`}
                        </p>
                        <p className="text-xs text-indigo-500 bg-indigo-50/50 p-3 rounded-xl mt-2 italic leading-relaxed">
                          <span className="font-bold not-italic mr-1">Explanation:</span> {q.explanation}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </section>

          {/* Reflection Section */}
          <section className="space-y-4">
            <h3 className="text-xl font-bold text-slate-800 flex items-center gap-2">
              <MessageSquareQuote className="w-6 h-6 text-indigo-500" /> Reflection
            </h3>
            <Textarea 
              placeholder="What challenged you today? What are your next steps?"
              value={reflection}
              onChange={(e) => setReflection(e.target.value)}
              className="rounded-3xl border-slate-200 bg-slate-50 min-h-[120px] p-6 text-slate-600 focus:ring-indigo-500 focus:border-indigo-500"
            />
          </section>

          <Button 
            onClick={handleFinish} 
            disabled={isSaving}
            className="w-full rounded-[2rem] py-8 bg-slate-900 hover:bg-slate-800 text-xl font-black shadow-xl"
          >
            {isSaving ? 'Saving...' : 'Finish'}
          </Button>
        </div>
      </motion.div>
    </div>
  );
}
